import {defineField, defineType} from 'sanity'
import {imageCaptionFields} from './imageCaptionFields'

export const artist = defineType({
  name: 'artist',
  title: '艺术家 / Artist',
  type: 'document',
  groups: [
    {name: 'pageTitle', title: '\u8be6\u60c5\u9875\u6807\u9898 / Page Title'},
    {name: 'profile', title: '基础信息 / Profile', default: true},
    {name: 'bio', title: '简介与经历 / Bio'},
    {name: 'sections', title: '详情分区 / Detail Sections'},
    {name: 'flags', title: '筛选状态 / Flags'},
    {name: 'legacy', title: '旧字段 / Legacy'},
    {name: 'admin', title: '后台管理 / Admin'},
  ],
  fields: [
    defineField({
      name: 'detailOverlineZh',
      title: '\u827a\u672f\u5bb6\u4ecb\u7ecd Overline\uff08\u4e2d\u6587\uff09 / Detail Overline (Chinese)',
      type: 'string',
      group: 'pageTitle',
      initialValue: '\u827a\u672f\u5bb6\u4ecb\u7ecd',
    }),
    defineField({
      name: 'detailOverlineEn',
      title: 'Detail Overline (English)',
      type: 'string',
      group: 'pageTitle',
      description: 'If empty, fallback to Chinese content.',
      initialValue: 'ARTIST PROFILE',
    }),
    defineField({
      name: 'detailTitleZh',
      title: '\u827a\u672f\u5bb6\u4ecb\u7ecd\u6807\u9898\uff08\u4e2d\u6587\uff09 / Detail Title (Chinese)',
      type: 'string',
      group: 'pageTitle',
      initialValue: '\u827a\u672f\u5bb6\u4ecb\u7ecd',
    }),
    defineField({
      name: 'detailTitleEn',
      title: 'Detail Title (English)',
      type: 'string',
      group: 'pageTitle',
      description: 'If empty, fallback to Chinese content.',
      initialValue: 'ARTIST PROFILE',
    }),
    defineField({
      name: 'nameZh',
      title: '姓名（中文） / Name Zh',
      type: 'string',
      group: 'profile',
    }),
    defineField({
      name: 'nameEn',
      title: '姓名（英文） / Name En',
      type: 'string',
      group: 'profile',
    }),
    defineField({
      name: 'slug',
      title: '链接标识 / Slug',
      type: 'slug',
      group: 'profile',
      options: {source: 'nameEn', maxLength: 96},
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'titleZh',
      title: '头衔（中文） / Title Zh',
      type: 'string',
      group: 'profile',
    }),
    defineField({
      name: 'titleEn',
      title: '头衔（英文） / Title En',
      type: 'string',
      group: 'profile',
    }),
    defineField({
      name: 'bioZh',
      title: '简介（中文） / Bio Zh',
      type: 'text',
      group: 'bio',
      rows: 6,
    }),
    defineField({
      name: 'bioEn',
      title: '简介（英文） / Bio En',
      type: 'text',
      group: 'bio',
      rows: 6,
    }),
    defineField({
      name: 'portrait',
      title: '肖像 / Portrait',
      type: 'image',
      group: 'profile',
      options: {hotspot: true},
      fields: imageCaptionFields,
    }),
    defineField({
      name: 'educationExperienceZh',
      title: '教育经历（中文） / Education Experience Zh',
      type: 'text',
      group: 'bio',
      rows: 5,
    }),
    defineField({
      name: 'educationExperienceEn',
      title: '教育经历（英文） / Education Experience En',
      type: 'text',
      group: 'bio',
      rows: 5,
    }),
    defineField({
      name: 'honorsZh',
      title: '荣誉和收藏（中文） / Honors Zh',
      type: 'text',
      group: 'sections',
      rows: 5,
    }),
    defineField({
      name: 'honorsEn',
      title: '荣誉和收藏（英文） / Honors En',
      type: 'text',
      group: 'sections',
      rows: 5,
    }),
    defineField({
      name: 'publicationsZh',
      title: '出版物（中文） / Publications Zh',
      type: 'text',
      group: 'sections',
      rows: 5,
    }),
    defineField({
      name: 'publicationsEn',
      title: '出版物（英文） / Publications En',
      type: 'text',
      group: 'sections',
      rows: 5,
    }),
    defineField({
      name: 'exhibitionsZh',
      title: '展览（中文） / Exhibitions Zh',
      type: 'text',
      group: 'sections',
      rows: 5,
    }),
    defineField({
      name: 'exhibitionsEn',
      title: '展览（英文） / Exhibitions En',
      type: 'text',
      group: 'sections',
      rows: 5,
    }),
    defineField({
      name: 'isTeamArtist',
      title: '是否为团队艺术家 / Is Team Artist',
      type: 'boolean',
      group: 'flags',
      initialValue: false,
    }),
    defineField({
      name: 'isResidentArtist',
      title: '是否为驻地艺术家 / Is Resident Artist',
      type: 'boolean',
      group: 'flags',
      initialValue: false,
    }),
    defineField({
      name: 'isTeamMember',
      title: '是否为团队成员（旧字段） / Is Team Member Legacy',
      type: 'boolean',
      group: 'legacy',
      initialValue: false,
      hidden: true,
    }),
    defineField({
      name: 'roleZh',
      title: '角色（旧字段，中文） / Role Zh Legacy',
      type: 'string',
      group: 'legacy',
      hidden: true,
    }),
    defineField({
      name: 'roleEn',
      title: '角色（旧字段，英文） / Role En Legacy',
      type: 'string',
      group: 'legacy',
      hidden: true,
    }),
    defineField({
      name: 'order',
      title: '排序 / Order',
      type: 'number',
      group: 'admin',
      initialValue: 0,
    }),
  ],
  orderings: [
    {
      title: '排序 / Order',
      name: 'orderAsc',
      by: [{field: 'order', direction: 'asc'}],
    },
  ],
  preview: {
    select: {
      title: 'nameZh',
      subtitle: 'titleZh',
      media: 'portrait',
    },
  },
})
