import {defineField, defineType} from 'sanity'
import {imageCaptionFields} from './imageCaptionFields'

export const event = defineType({
  name: 'event',
  title: '活动 / Event',
  type: 'document',
  groups: [
    {name: 'basic', title: '基础信息 / Basic', default: true},
    {name: 'media', title: '图片 / Media'},
    {name: 'card', title: '列表卡片 / Card'},
    {name: 'detail', title: '详情内容 / Detail'},
    {name: 'legacy', title: '旧字段 / Legacy'},
    {name: 'admin', title: '后台管理 / Admin'},
  ],
  fields: [
    defineField({
      name: 'titleZh',
      title: '标题（中文） / Title Zh',
      type: 'string',
      group: 'basic',
    }),
    defineField({
      name: 'titleEn',
      title: '标题（英文） / Title En',
      type: 'string',
      group: 'basic',
    }),
    defineField({
      name: 'slug',
      title: '链接标识 / Slug',
      type: 'slug',
      group: 'basic',
      options: {source: 'titleEn', maxLength: 96},
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'eventType',
      title: '活动类型 / Event Type',
      type: 'string',
      group: 'basic',
      options: {
        list: [
          {title: '线下体验 / Offline Experience', value: 'offline-experience'},
          {title: '艺术公开课 / Open Class', value: 'open-class'},
          {title: '活动 / Activity', value: 'activity'},
        ],
        layout: 'radio',
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'coverImage',
      title: '封面图片 / Cover Image',
      type: 'image',
      group: 'media',
      options: {hotspot: true},
      fields: imageCaptionFields,
    }),
    defineField({
      name: 'posterImage',
      title: '海报图片 / Poster Image',
      type: 'image',
      group: 'media',
      options: {hotspot: true},
      fields: imageCaptionFields,
    }),
    defineField({
      name: 'teachingSpaceZh',
      title: '教学空间（中文） / Teaching Space Zh',
      type: 'text',
      group: 'detail',
      rows: 4,
    }),
    defineField({
      name: 'teachingSpaceEn',
      title: '教学空间（英文） / Teaching Space En',
      type: 'text',
      group: 'detail',
      rows: 4,
    }),
    defineField({
      name: 'courseIntroZh',
      title: '课程介绍（中文） / Course Intro Zh',
      type: 'text',
      group: 'card',
      rows: 5,
    }),
    defineField({
      name: 'courseIntroEn',
      title: '课程介绍（英文） / Course Intro En',
      type: 'text',
      group: 'card',
      rows: 5,
    }),
    defineField({
      name: 'feesZh',
      title: '收费情况（中文） / Fees Zh',
      type: 'text',
      group: 'detail',
      rows: 4,
    }),
    defineField({
      name: 'feesEn',
      title: '收费情况（英文） / Fees En',
      type: 'text',
      group: 'detail',
      rows: 4,
    }),
    defineField({
      name: 'facultyZh',
      title: '学术主持 / 师资（中文） / Faculty Zh',
      type: 'text',
      group: 'card',
      rows: 5,
    }),
    defineField({
      name: 'facultyEn',
      title: '学术主持 / 师资（英文） / Faculty En',
      type: 'text',
      group: 'card',
      rows: 5,
    }),
    defineField({
      name: 'outcomesZh',
      title: '成果赏析（中文） / Outcomes Zh',
      type: 'text',
      group: 'detail',
      rows: 5,
    }),
    defineField({
      name: 'outcomesEn',
      title: '成果赏析（英文） / Outcomes En',
      type: 'text',
      group: 'detail',
      rows: 5,
    }),
    defineField({
      name: 'contentZh',
      title: '活动内容（中文） / Content Zh',
      type: 'text',
      group: 'detail',
      rows: 7,
    }),
    defineField({
      name: 'contentEn',
      title: '活动内容（英文） / Content En',
      type: 'text',
      group: 'detail',
      rows: 7,
    }),
    defineField({
      name: 'galleryImages',
      title: '活动图库 / Gallery Images',
      type: 'array',
      group: 'detail',
      of: [{type: 'image', options: {hotspot: true}, fields: imageCaptionFields}],
    }),
    defineField({
      name: 'date',
      title: '日期（旧字段） / Date Legacy',
      type: 'datetime',
      group: 'legacy',
      hidden: true,
    }),
    defineField({
      name: 'locationZh',
      title: '地点（旧字段，中文） / Location Zh Legacy',
      type: 'string',
      group: 'legacy',
      hidden: true,
    }),
    defineField({
      name: 'locationEn',
      title: '地点（旧字段，英文） / Location En Legacy',
      type: 'string',
      group: 'legacy',
      hidden: true,
    }),
    defineField({
      name: 'isFeatured',
      title: '是否精选（旧字段） / Is Featured Legacy',
      type: 'boolean',
      group: 'legacy',
      initialValue: false,
      hidden: true,
    }),
    defineField({
      name: 'order',
      title: '排序 / Order',
      type: 'number',
      group: 'admin',
      initialValue: 0,
    }),
  ],
  orderings: [
    {
      title: '排序 / Order',
      name: 'orderAsc',
      by: [{field: 'order', direction: 'asc'}],
    },
  ],
  preview: {
    select: {
      title: 'titleZh',
      media: 'coverImage',
    },
    prepare({title, media}) {
      return {
        title,
        media,
      }
    },
  },
})
