import {defineField, defineType} from 'sanity'

export const homePage = defineType({
  name: 'homePage',
  title: '首页 / Home Page',
  type: 'document',
  groups: [
    {name: 'hero', title: 'Hero 首屏', default: true},
    {name: 'intro', title: '简介区 / Intro'},
    {name: 'featured', title: '首页推荐 / Featured'},
    {name: 'legacy', title: '旧字段 / Legacy'},
  ],
  fields: [
    defineField({
      name: 'heroTitleZh',
      title: '主标题（中文） / Hero Title Zh',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroTitleEn',
      title: '主标题（英文） / Hero Title En',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroSubtitleZh',
      title: '副标题（中文） / Hero Subtitle Zh',
      type: 'text',
      group: 'hero',
      rows: 2,
    }),
    defineField({
      name: 'heroSubtitleEn',
      title: '副标题（英文） / Hero Subtitle En',
      type: 'text',
      group: 'hero',
      rows: 2,
    }),
    defineField({
      name: 'heroImage',
      title: '首页主图 / Hero Image',
      type: 'image',
      group: 'hero',
      options: {hotspot: true},
    }),
    defineField({
      name: 'introTitleZh',
      title: '介绍标题（中文） / Intro Title Zh',
      type: 'string',
      group: 'intro',
    }),
    defineField({
      name: 'introTitleEn',
      title: '介绍标题（英文） / Intro Title En',
      type: 'string',
      group: 'intro',
    }),
    defineField({
      name: 'introTextZh',
      title: '介绍正文（中文） / Intro Text Zh',
      type: 'text',
      group: 'intro',
      rows: 4,
    }),
    defineField({
      name: 'introTextEn',
      title: '介绍正文（英文） / Intro Text En',
      type: 'text',
      group: 'intro',
      rows: 4,
    }),
    defineField({
      name: 'featuredStudyPrograms',
      title: '精选研学 / Featured Study Programs',
      type: 'array',
      group: 'featured',
      of: [{type: 'reference', to: [{type: 'studyProgram'}]}],
    }),
    defineField({
      name: 'featuredEvents',
      title: '精选活动 / Featured Events',
      type: 'array',
      group: 'featured',
      of: [{type: 'reference', to: [{type: 'event'}]}],
    }),
    defineField({
      name: 'featuredArtWorks',
      title: '精选艺术作品 / Featured Art Works',
      type: 'array',
      group: 'featured',
      of: [{type: 'reference', to: [{type: 'artWork'}]}],
    }),
    defineField({
      name: 'featuredProducts',
      title: '精选商品 / Featured Products',
      type: 'array',
      group: 'featured',
      of: [{type: 'reference', to: [{type: 'product'}]}],
    }),
    defineField({
      name: 'featuredResidency',
      title: '精选驻地计划（旧字段） / Featured Residency Legacy',
      type: 'reference',
      to: [{type: 'residencyPage'}],
      group: 'legacy',
      hidden: true,
    }),
    defineField({
      name: 'featuredArtProjects',
      title: '精选艺术项目（旧字段） / Featured Art Projects Legacy',
      type: 'array',
      of: [{type: 'reference', to: [{type: 'artProject'}]}],
      group: 'legacy',
      hidden: true,
    }),
  ],
  preview: {
    select: {
      title: 'heroTitleZh',
      subtitle: 'heroTitleEn',
      media: 'heroImage',
    },
  },
})
