import {defineField, defineType} from 'sanity'

export const homePage = defineType({
  name: 'homePage',
  title: '棣栭〉 / Home Page',
  type: 'document',
  groups: [
    {name: 'hero', title: 'Hero 棣栧睆', default: true},
    {name: 'intro', title: '绠€浠嬪尯 / Intro'},
    {name: 'featured', title: '棣栭〉鎺ㄨ崘 / Featured'},
    {name: 'legacy', title: '鏃у瓧娈?/ Legacy'},
  ],
  fields: [
    defineField({
      name: 'heroTitleZh',
      title: '涓绘爣棰橈紙涓枃锛?/ Hero Title Zh',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroTitleEn',
      title: '涓绘爣棰橈紙鑻辨枃锛?/ Hero Title En',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroSubtitleZh',
      title: '鍓爣棰橈紙涓枃锛?/ Hero Subtitle Zh',
      type: 'text',
      group: 'hero',
      rows: 2,
    }),
    defineField({
      name: 'heroSubtitleEn',
      title: '鍓爣棰橈紙鑻辨枃锛?/ Hero Subtitle En',
      type: 'text',
      group: 'hero',
      rows: 2,
    }),
    defineField({
      name: 'heroImage',
      title: '棣栭〉涓诲浘 / Hero Image',
      type: 'image',
      group: 'hero',
      options: {hotspot: true},
      hidden: true,
    }),
    defineField({
      name: 'heroImages',
      title: '棣栭〉涓昏瑙夎疆鎾浘 / Hero Carousel Images',
      type: 'array',
      group: 'hero',
      of: [
        defineField({
          name: 'heroCarouselImage',
          title: '棣栭〉 Banner 鍥剧墖 / Hero Banner Image',
          type: 'image',
          options: {hotspot: true},
          fields: [
            defineField({
              name: 'alt',
              title: '鏇夸唬鏂囧瓧 / Alt Text',
              type: 'string',
            }),
            defineField({
              name: 'titleLogoWhite',
              title: '白色标题 PNG / White Title Logo',
              type: 'image',
              description: '上传透明底白色单色 PNG，用于深色 Banner 图片。',
              options: {hotspot: false},
            }),
            defineField({
              name: 'titleLogoBlack',
              title: '黑色标题 PNG / Black Title Logo',
              type: 'image',
              description: '上传透明底黑色单色 PNG，用于浅色 Banner 图片。',
              options: {hotspot: false},
            }),
            defineField({
              name: 'titleLogo',
              title: '标题 PNG（旧字段，兼容） / Legacy Title Logo',
              type: 'image',
              description: '旧版单色 PNG 字段，仅用于兼容已有数据。新内容请使用 White / Black Title Logo。',
              options: {hotspot: false},
              hidden: true,
            }),
            defineField({
              name: 'titleColorMode',
              title: '标题颜色模式 / Title Color Mode',
              type: 'string',
              initialValue: 'black',
              options: {
                list: [
                  {title: '黑色 / Black', value: 'black'},
                  {title: '白色 / White', value: 'white'},
                ],
                layout: 'radio',
              },
            }),
          ],
        }),
      ],
    }),
    defineField({
      name: 'introTitleZh',
      title: '浠嬬粛鏍囬锛堜腑鏂囷級 / Intro Title Zh',
      type: 'string',
      group: 'intro',
    }),
    defineField({
      name: 'introTitleEn',
      title: '浠嬬粛鏍囬锛堣嫳鏂囷級 / Intro Title En',
      type: 'string',
      group: 'intro',
    }),
    defineField({
      name: 'introTextZh',
      title: '浠嬬粛姝ｆ枃锛堜腑鏂囷級 / Intro Text Zh',
      type: 'text',
      group: 'intro',
      rows: 4,
    }),
    defineField({
      name: 'introTextEn',
      title: '浠嬬粛姝ｆ枃锛堣嫳鏂囷級 / Intro Text En',
      type: 'text',
      group: 'intro',
      rows: 4,
    }),
    defineField({
      name: 'featuredStudyPrograms',
      title: '绮鹃€夌爺瀛?/ Featured Study Programs',
      type: 'array',
      group: 'featured',
      of: [{type: 'reference', to: [{type: 'studyProgram'}]}],
    }),
    defineField({
      name: 'featuredEvents',
      title: '绮鹃€夋椿鍔?/ Featured Events',
      type: 'array',
      group: 'featured',
      of: [{type: 'reference', to: [{type: 'event'}]}],
    }),
    defineField({
      name: 'featuredArtWorks',
      title: '绮鹃€夎壓鏈綔鍝?/ Featured Art Works',
      type: 'array',
      group: 'featured',
      of: [{type: 'reference', to: [{type: 'artWork'}]}],
    }),
    defineField({
      name: 'featuredProducts',
      title: '绮鹃€夊晢鍝?/ Featured Products',
      type: 'array',
      group: 'featured',
      of: [{type: 'reference', to: [{type: 'product'}]}],
    }),
    defineField({
      name: 'featuredResidency',
      title: '绮鹃€夐┗鍦拌鍒掞紙鏃у瓧娈碉級 / Featured Residency Legacy',
      type: 'reference',
      to: [{type: 'residencyPage'}],
      group: 'legacy',
      hidden: true,
    }),
    defineField({
      name: 'featuredArtProjects',
      title: '绮鹃€夎壓鏈」鐩紙鏃у瓧娈碉級 / Featured Art Projects Legacy',
      type: 'array',
      of: [{type: 'reference', to: [{type: 'artProject'}]}],
      group: 'legacy',
      hidden: true,
    }),
  ],
  preview: {
    select: {
      title: 'heroTitleZh',
      subtitle: 'heroTitleEn',
      media: 'heroImages.0',
    },
  },
})

