import {defineField, defineType} from 'sanity'
import {imageCaptionFields} from './imageCaptionFields'

const englishFallbackDescription = 'If empty, fallback to Chinese content.'

export const teamMember = defineType({
  name: 'teamMember',
  title: '\u56e2\u961f\u6210\u5458 / Team Member',
  type: 'document',
  groups: [
    {
      name: 'card',
      title: '\u5217\u8868\u9875\u5361\u7247\u4fe1\u606f / Card Info',
      default: true,
    },
    {
      name: 'detail',
      title: '\u8be6\u60c5\u9875\u5185\u5bb9 / Detail Page Info',
    },
    {
      name: 'compatibility',
      title: '\u517c\u5bb9\u5173\u8054 / Compatibility',
    },
  ],
  fields: [
    defineField({
      name: 'nameZh',
      title: '\u59d3\u540d\uff08\u4e2d\u6587\uff09 / Name (Chinese)',
      type: 'string',
      group: ['card', 'detail'],
    }),
    defineField({
      name: 'nameEn',
      title: 'Name (English)',
      type: 'string',
      group: ['card', 'detail'],
      description: englishFallbackDescription,
    }),
    defineField({
      name: 'roleZh',
      title: '\u804c\u4f4d\uff08\u4e2d\u6587\uff09 / Role (Chinese)',
      type: 'string',
      group: ['card', 'detail'],
    }),
    defineField({
      name: 'roleEn',
      title: 'Role (English)',
      type: 'string',
      group: ['card', 'detail'],
      description: englishFallbackDescription,
    }),
    defineField({
      name: 'portrait',
      title: '\u8096\u50cf / Portrait',
      type: 'image',
      group: ['card', 'detail'],
      options: {hotspot: true},
      fields: imageCaptionFields,
    }),
    defineField({
      name: 'shortBioZh',
      title: '\u5361\u7247\u7b80\u4ecb\uff08\u4e2d\u6587\uff09 / Short Bio (Chinese)',
      type: 'text',
      group: 'card',
      rows: 3,
    }),
    defineField({
      name: 'shortBioEn',
      title: 'Short Bio (English)',
      type: 'text',
      group: 'card',
      rows: 3,
      description: englishFallbackDescription,
    }),
    defineField({
      name: 'slug',
      title: '\u94fe\u63a5\u6807\u8bc6 / Slug',
      type: 'slug',
      group: 'detail',
      description: '\u4fdd\u5b58\u540e\u5c3d\u91cf\u4e0d\u8981\u4fee\u6539\u3002',
      options: {source: 'nameEn', maxLength: 96},
    }),
    defineField({
      name: 'detailPageTitleZh',
      title: '\u8be6\u60c5\u9875\u6807\u9898\uff08\u4e2d\u6587\uff09 / Detail Page Title (Chinese)',
      type: 'string',
      group: 'detail',
      initialValue: '\u827a\u672f\u5bb6\u4ecb\u7ecd',
    }),
    defineField({
      name: 'detailPageTitleEn',
      title: 'Detail Page Title (English)',
      type: 'string',
      group: 'detail',
      initialValue: 'ARTIST PROFILE',
    }),
    defineField({
      name: 'genderZh',
      title: '\u6027\u522b\uff08\u4e2d\u6587\uff09 / Gender (Chinese)',
      type: 'string',
      group: 'detail',
    }),
    defineField({
      name: 'genderEn',
      title: 'Gender (English)',
      type: 'string',
      group: 'detail',
      description: englishFallbackDescription,
    }),
    defineField({
      name: 'birthDateTextZh',
      title: '\u51fa\u751f\u5e74\u6708\uff08\u4e2d\u6587\uff09 / Birth Date Text (Chinese)',
      type: 'string',
      group: 'detail',
    }),
    defineField({
      name: 'birthDateTextEn',
      title: 'Birth Date Text (English)',
      type: 'string',
      group: 'detail',
      description: englishFallbackDescription,
    }),
    defineField({
      name: 'bioZh',
      title: '\u57fa\u672c\u4ecb\u7ecd\u6b63\u6587\uff08\u4e2d\u6587\uff09 / Bio (Chinese)',
      type: 'text',
      group: 'detail',
      rows: 6,
    }),
    defineField({
      name: 'bioEn',
      title: 'Bio (English)',
      type: 'text',
      group: 'detail',
      rows: 6,
      description: englishFallbackDescription,
    }),
    defineField({
      name: 'honorsCollectionsZh',
      title: '\u8363\u8a89\u548c\u6536\u85cf\uff08\u4e2d\u6587\uff09 / Honors and Collections (Chinese)',
      type: 'text',
      group: 'detail',
      rows: 5,
    }),
    defineField({
      name: 'honorsCollectionsEn',
      title: 'Honors and Collections (English)',
      type: 'text',
      group: 'detail',
      rows: 5,
      description: englishFallbackDescription,
    }),
    defineField({
      name: 'researchProjectsZh',
      title: '\u8bfe\u9898\uff08\u4e2d\u6587\uff09 / Research Projects (Chinese)',
      type: 'text',
      group: 'detail',
      rows: 5,
    }),
    defineField({
      name: 'researchProjectsEn',
      title: 'Research Projects (English)',
      type: 'text',
      group: 'detail',
      rows: 5,
      description: englishFallbackDescription,
    }),
    defineField({
      name: 'writingsZh',
      title: '\u8457\u4f5c\uff08\u4e2d\u6587\uff09 / Writings (Chinese)',
      type: 'text',
      group: 'detail',
      rows: 5,
    }),
    defineField({
      name: 'writingsEn',
      title: 'Writings (English)',
      type: 'text',
      group: 'detail',
      rows: 5,
      description: englishFallbackDescription,
    }),
    defineField({
      name: 'publicationsZh',
      title: '\u51fa\u7248\uff08\u4e2d\u6587\uff09 / Publications (Chinese)',
      type: 'text',
      group: 'detail',
      rows: 5,
    }),
    defineField({
      name: 'publicationsEn',
      title: 'Publications (English)',
      type: 'text',
      group: 'detail',
      rows: 5,
      description: englishFallbackDescription,
    }),
    defineField({
      name: 'exhibitionsZh',
      title: '\u5c55\u89c8\uff08\u4e2d\u6587\uff09 / Exhibitions (Chinese)',
      type: 'text',
      group: 'detail',
      rows: 5,
    }),
    defineField({
      name: 'exhibitionsEn',
      title: 'Exhibitions (English)',
      type: 'text',
      group: 'detail',
      rows: 5,
      description: englishFallbackDescription,
    }),
    defineField({
      name: 'galleryImages',
      title: '\u76f8\u5173\u56fe\u7247 / Related Images',
      type: 'array',
      group: 'detail',
      of: [{type: 'image', options: {hotspot: true}, fields: imageCaptionFields}],
    }),
    defineField({
      name: 'detailBioZh',
      title: '\u65e7\u8be6\u60c5\u7b80\u4ecb\uff08\u4e2d\u6587\uff09 / Legacy Detail Bio (Chinese)',
      type: 'text',
      group: 'compatibility',
      rows: 6,
    }),
    defineField({
      name: 'detailBioEn',
      title: 'Legacy Detail Bio (English)',
      type: 'text',
      group: 'compatibility',
      rows: 6,
    }),
    defineField({
      name: 'educationExperienceZh',
      title: '\u6559\u80b2\u7ecf\u5386\uff08\u4e2d\u6587\uff09 / Education Experience (Chinese)',
      type: 'text',
      group: 'compatibility',
      rows: 5,
    }),
    defineField({
      name: 'educationExperienceEn',
      title: 'Education Experience (English)',
      type: 'text',
      group: 'compatibility',
      rows: 5,
    }),
    defineField({
      name: 'honorsZh',
      title: '\u65e7\u8363\u8a89\u548c\u6536\u85cf\uff08\u4e2d\u6587\uff09 / Legacy Honors (Chinese)',
      type: 'text',
      group: 'compatibility',
      rows: 5,
    }),
    defineField({
      name: 'honorsEn',
      title: 'Legacy Honors (English)',
      type: 'text',
      group: 'compatibility',
      rows: 5,
    }),
    defineField({
      name: 'linkedArtist',
      title: '\u517c\u5bb9\u5173\u8054\u827a\u672f\u5bb6 / Linked Artist',
      type: 'reference',
      group: 'compatibility',
      to: [{type: 'artist'}],
    }),
    defineField({
      name: 'isFeatured',
      title: '\u662f\u5426\u7cbe\u9009 / Is Featured',
      type: 'boolean',
      group: 'detail',
      initialValue: false,
    }),
    defineField({
      name: 'order',
      title: '\u6392\u5e8f / Order',
      type: 'number',
      group: ['card', 'detail'],
      initialValue: 0,
    }),
  ],
  orderings: [
    {
      title: '\u6392\u5e8f / Order',
      name: 'orderAsc',
      by: [{field: 'order', direction: 'asc'}],
    },
  ],
  preview: {
    select: {
      title: 'nameZh',
      subtitle: 'roleZh',
      media: 'portrait',
    },
  },
})
